security:
  # Rate Limiting Configuration
  rate_limiting:
    default:
      rate: 100  # requests per minute
      burst: 20   # burst size
    endpoints:
      /feed:
        rate: 60
        burst: 10
      /validate:
        rate: 30
        burst: 5
      /metrics:
        rate: 300
        burst: 50

  # Access Control
  access_control:
    jwt:
      issuer: "atf.algorithmictransparency.gov"
      audience: "atf-service"
      algorithms: ["RS256"]
      key_rotation_interval: "24h"
    cors:
      allowed_origins:
        - "https://algorithmictransparency.gov"
        - "https://*.algorithmictransparency.gov"
      allowed_methods: ["GET", "POST", "PUT", "DELETE"]
      allowed_headers: ["Authorization", "Content-Type"]
      max_age: 3600
    ip_whitelist:
      enabled: true
      allowed_ranges:
        - "10.0.0.0/8"    # Internal network
        - "172.16.0.0/12" # Docker network
        - "192.168.0.0/16" # Local network

  # Content Security
  content_security:
    policies:
      default_src: ["'self'"]
      script_src: ["'self'"]
      style_src: ["'self'"]
      img_src: ["'self'"]
      font_src: ["'self'"]
      frame_ancestors: ["'none'"]
      form_action: ["'self'"]
    headers:
      X-Frame-Options: "DENY"
      X-Content-Type-Options: "nosniff"
      X-XSS-Protection: "1; mode=block"
      Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"

  # Feed Authentication
  feed_auth:
    signatures:
      enabled: true
      algorithm: "RSA-SHA256"
      key_size: 2048
      validity_period: "7d"
    certificate:
      provider: "atf-authority"
      validity: "1y"
      renewal_before: "30d"

  # Encryption
  encryption:
    tls:
      min_version: "1.2"
      preferred_ciphers:
        - "TLS_AES_128_GCM_SHA256"
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_CHACHA20_POLY1305_SHA256"
    data:
      algorithm: "AES-256-GCM"
      key_rotation: "90d"

  # Audit Logging
  audit:
    enabled: true
    events:
      - feed_generation
      - feed_validation
      - authentication
      - authorization
      - key_rotation
    retention: "1y"
    format: "JSON"